**Bài Kiểm Tra Điểm B**
* Họ tên sinh viên: Trịnh Thế Vũ
* Mã sinh viên: 1821050886
* Lớp/Nhóm môn học: 7080510/03
* Email: trinhvuthe@gmail.com

In [74]:
#đọc dữ liệu từ file csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

path_practice4 = "Data/Data_Practice4_ok.csv"
df_practice4 = pd.read_csv(path_practice4)
df_practice4.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Age      961 non-null    int64
 1   Shape    961 non-null    int64
 2   Margin   961 non-null    int64
 3   Density  961 non-null    int64
 4   Target   961 non-null    int64
dtypes: int64(5)
memory usage: 37.7 KB


In [56]:
#Hiển thị 5 dòng dữ liệu của Dataset
df_practice4.head()

Age  Shape  Margin  Density  Target
0    3      3       2        0       1
1    1      1       0        0       1
2    2      0       2        0       1
3    0      1       0        0       0
4    3      1       2        0       1

In [57]:
#Tách biến độc lập - biến phụ thuộc
#1.Tách biến độc lập X_pratice4
X_pratice4 = df_practice4.iloc[:,1:].values
X_pratice4

array([[3, 2, 0, 1],
       [1, 0, 0, 1],
       [0, 2, 0, 1],
       ...,
       [0, 2, 0, 0],
       [0, 2, 0, 1],
       [3, 3, 0, 0]], dtype=int64)

In [58]:
X_pratice4.shape


(961, 4)

In [59]:
#2.Tách biến phụ thuộc Y_practice
Y_practice4 = df_practice4.iloc[:,0].values
Y_practice4

array([3, 1, 2, 0, 3, 2, 3, 1, 2, 2, 3, 1, 2, 1, 2, 2, 2, 2, 2, 1, 3, 2,
       1, 1, 2, 3, 3, 2, 1, 2, 1, 2, 2, 1, 4, 3, 2, 3, 1, 2, 2, 3, 2, 2,
       2, 1, 2, 0, 1, 3, 3, 3, 0, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 3, 0,
       1, 3, 1, 2, 3, 3, 2, 3, 3, 0, 3, 2, 2, 3, 3, 1, 3, 2, 2, 0, 2, 1,
       2, 2, 3, 3, 3, 2, 2, 2, 1, 1, 2, 0, 2, 2, 2, 0, 2, 2, 1, 0, 2, 0,
       1, 3, 2, 2, 1, 2, 1, 2, 2, 4, 2, 1, 0, 3, 0, 2, 3, 1, 2, 1, 3, 3,
       4, 2, 3, 1, 2, 2, 2, 3, 3, 2, 1, 1, 2, 2, 2, 2, 3, 1, 2, 3, 3, 1,
       0, 2, 2, 2, 2, 2, 3, 1, 0, 2, 1, 4, 3, 2, 2, 4, 0, 1, 2, 1, 2, 2,
       2, 1, 3, 1, 1, 3, 0, 1, 3, 3, 1, 3, 4, 2, 0, 3, 2, 1, 2, 4, 1, 3,
       3, 2, 1, 1, 2, 1, 2, 3, 1, 1, 2, 3, 1, 3, 2, 1, 3, 1, 2, 2, 1, 1,
       1, 1, 2, 3, 2, 1, 2, 2, 2, 1, 3, 3, 3, 2, 2, 1, 2, 2, 2, 0, 3, 2,
       1, 0, 3, 1, 1, 2, 1, 1, 0, 2, 1, 3, 2, 3, 3, 3, 3, 3, 2, 1, 1, 1,
       3, 2, 3, 2, 3, 2, 3, 2, 3, 3, 2, 3, 3, 1, 3, 2, 1, 1, 1, 3, 2, 2,
       3, 1, 2, 2, 3, 1, 1, 3, 2, 3, 0, 2, 3, 1, 1,

In [60]:
Y_practice4.shape

(961,)

In [61]:
#Tách thành tập Train-Test theo tỷ lệ 75-25:
from sklearn.model_selection import train_test_split
X_practice4_train, X_practice4_test, Y_practice4_train, Y_practice4_test = train_test_split(X_pratice4,
                                                                                   Y_practice4,
                                                                                   test_size = 0.25,
                                                                                   random_state=42)
print('1. Kích thước tập training:',X_practice4_train.shape)
print('2. Kích thước tập test:',X_practice4_test.shape)





1. Kích thước tập training: (720, 4)
2. Kích thước tập test: (241, 4)


In [62]:
#Xây dựng model và huấn luyện:
from sklearn.neighbors import KNeighborsClassifier

#Khai bao model voi cac tham so mac dinh:
KNN_practice4 = KNeighborsClassifier()

#huan luyen vowis tajp train:
KNN_practice4.fit(X_practice4_train,Y_practice4_train)

#Do chisnh xasc
acc_train = KNN_practice4.score(X_practice4_train,Y_practice4_train)
print('Do chinh xac tren tap hl:',round(acc_train*100,2))

Do chinh xac tren tap hl: 40.14


In [63]:
#Dự đoán trên tập test
Y_practice4_predic = KNN_practice4.predict(X_pratice4_test)

#kiem tra kq du doan:
print('Gia tri that:',Y_practice4_test[:30] )
print('Mo hinh du doan:',Y_practice4_predic[:30] )



Gia tri that: [2 2 1 0 1 2 1 2 2 3 2 3 1 1 2 2 1 1 1 3 2 2 2 2 2 1 3 2 3 3]
Mo hinh du doan: [0 3 3 0 2 1 0 0 3 1 0 3 1 2 1 0 2 0 1 3 3 3 2 2 1 3 3 3 3 1]


In [64]:
#Đánh giá độ chính xác:
from sklearn.metrics import accuracy_score
acc_practice4 = accuracy_score(Y_practice4_test,Y_practice4_predic)
print('do chinh xac cua mo hinh tren tap Test:',round(acc_practice4*100,2))



do chinh xac cua mo hinh tren tap Test: 32.37


In [65]:
#Đếm số mẫu dự đoán đúng
acc_practice = accuracy_score(Y_practice4_test,Y_practice4_predic, normalize=False)
print('so mau du doan dung  tren tap test:',acc_practice,'/',len(Y_practice4_test))


so mau du doan dung  tren tap test: 78 / 241


In [66]:
#Đếm số lượng theo từng lớp trong tập Test
from collections import Counter

print('Tổng số mẫu tập Test:', len(Y_practice4_test))
print(Counter(Y_practice4_test))

Tổng số mẫu tập Test: 241
Counter({2: 107, 1: 63, 3: 45, 0: 21, 4: 5})


In [67]:
#Đếm số mẫu dự đoán đúng
acc_practice1 = accuracy_score(Y_practice4_test, Y_practice4_predic,normalize=False)
print('Tổng số mẫu dự đoán đúng trên tập Test:', acc_practice1, ' /', len(Y_practice4_test))

Tổng số mẫu dự đoán đúng trên tập Test: 78  / 241


In [68]:
#Sử dụng ma trận confussion matrix kiểm tra kết quả:
from sklearn.metrics import confusion_matrix
cnf_matrix_titanic = confusion_matrix(Y_practice4_test,Y_practice4_predic,)
print('Confusion matrix - Titanic:')
print(cnf_matrix_titanic)

Confusion matrix - Titanic:
[[ 8  1  9  3  0]
 [15 16 20 12  0]
 [21 21 35 30  0]
 [ 3 16  7 19  0]
 [ 0  1  2  2  0]]


In [69]:
#Thay đổi các tham số của model: đánh giá độ chính xác
# Thay đổi tham số n_neighbors, weights:
KNN_practice = KNeighborsClassifier(n_neighbors=15, 
                                     weights='distance')

#Thực hiện huấn luyện với dữ liệu tập train
KNN_practice.fit(X_practice4_train,Y_practice4_train)

#Sử dụng mô hình huấn luyện dự đoán trên tập dữ liệu Test
Y_predic2 = KNN_practice.predict(X_practice4_test)
print("Kết quả phân tích trên tập dữ liệu TEST:")
print("Mô hình dự đoán: ", Y_practice4_test[:30])
print("Thực tế    : ", Y_predic2[:30])

acc_practice21 = accuracy_score(Y_practice4_test, Y_predic2)
print('Độ chính xác của mô hình practice (k=15, weights=distance):', acc_practice21)
print('Độ chính xác theo %:', round(acc_practice21*100,2))

Kết quả phân tích trên tập dữ liệu TEST:
Mô hình dự đoán:  [2 2 1 0 1 2 1 2 2 3 2 3 1 1 2 2 1 1 1 3 2 2 2 2 2 1 3 2 3 3]
Thực tế    :  [2 2 2 2 2 2 2 2 3 2 2 2 2 2 1 2 2 2 1 2 3 3 2 2 2 3 2 3 2 1]
Độ chính xác của mô hình practice (k=15, weights=distance): 0.4190871369294606
Độ chính xác theo %: 41.91


In [70]:
acc_practice22 = accuracy_score(Y_practice4_test, Y_predic2, normalize=False)
print('Tổng số mẫu dự đoán đúng:', acc_practice22, ' /', len(Y_practice4_test))

Tổng số mẫu dự đoán đúng: 101  / 241
